import { SavedExample } from './types';

export interface ExampleProject {
  id: string;
  name: string;
  type: string;
  stack: string[];
  roughNotes: string;
  cvLine: string;
  interviewPreview: string;
  fullPitch: SavedExample['pitch'];
}

export const exampleProjects: ExampleProject[] = [
  {
    id: '1',
    name: 'InvoiceFlow Play',
    type: 'SaaS',
    stack: ['Next.js', 'Stripe', 'PostgreSQL', 'TypeScript'],
    roughNotes: 'built a billing thing\nhandles subscriptions\nstripe integration\nusers can manage plans\ngot webhooks working\nfixed some race conditions with concurrent updates',
    cvLine: 'Built InvoiceFlow Play, a SaaS billing platform handling subscription lifecycle management, plan upgrades, and payment processing. Integrated Stripe webhooks with idempotency keys and fixed a race condition in concurrent subscription updates using optimistic locking.',
    interviewPreview: 'InvoiceFlow Play is a billing platform I built to handle the stuff Stripe doesn\'t give you out of the box — plan changes, proration, and the edge cases that break when two requests touch the same subscription at the same time.',
    fullPitch: {
      elevatorPitch: 'InvoiceFlow Play is a SaaS billing tool I built to handle the subscription lifecycle that Stripe leaves up to you — plan changes, proration, concurrent update conflicts, and a customer portal. Stack: Next.js, Stripe, PostgreSQL, TypeScript.',
      cvDescription: 'Built InvoiceFlow Play, a SaaS billing platform handling subscription lifecycle management, plan upgrades/downgrades, and real-time payment processing. Integrated Stripe webhooks with idempotency keys to prevent duplicate charges on retries. Resolved a race condition where concurrent subscription updates corrupted plan state — fixed with database-level optimistic locking. Stack: Next.js, TypeScript, Stripe, PostgreSQL.',
      linkedInDescription: 'Shipped InvoiceFlow Play — a billing platform I built from scratch.\n\nStripe handles payments well, but not the business logic around them: mid-cycle plan changes, prorated credits, or what happens when two requests hit the same subscription simultaneously.\n\nThe hardest bug I fixed: a race condition that occasionally double-charged users on plan upgrades. Two concurrent writes, no lock. Fixed it with optimistic locking at the database level — added a version column and a conditional update that retries on conflict.\n\nThe webhook handler was the other tricky piece. Network retries mean the same event can arrive twice. Idempotency keys on every Stripe API call made that safe.\n\nStack: Next.js · Stripe · PostgreSQL · TypeScript',
      interviewAnswer: 'InvoiceFlow Play came out of a gap I kept running into — Stripe gives you great primitives, but it doesn\'t handle the business logic of subscription management for you.\n\nI built plan change flows with proration, webhook handling with idempotency keys, and a billing portal for customers to manage their own subscriptions.\n\nThe trickiest part was a race condition in plan upgrades. If two requests hit at the same time — say a user double-clicks or there\'s a network retry — the subscription state would get corrupted. I diagnosed it by writing test tooling that reproduced the timing, then fixed it with optimistic locking in PostgreSQL: a version column plus a conditional update that retries on conflict.\n\nIf I rebuilt it I\'d add a proper event log. Right now debugging billing issues means grepping application logs, which is slow and error-prone.',
      technicalBreakdown: {
        architecture: 'Next.js app with a PostgreSQL database. API routes handle Stripe webhook events, plan changes, and customer portal sessions. Subscription state lives in the DB — Stripe is the source of truth for payment status, but we maintain our own plan history for the UI and reporting.',
        keyDecisions: 'Idempotency keys on every Stripe API call so retries don\'t cause duplicate charges. PostgreSQL over a document store because subscription data — plan history, invoice lines, customer records — has relational constraints that are hard to enforce otherwise. Webhook handler kept synchronous and simple; anything expensive moves to background jobs.',
        problemsSolved: 'Race condition on concurrent plan updates: two requests would read the current plan, both decide to apply a change, and both write back — corrupting state. Fixed with optimistic locking. Webhooks arriving out of order: solved by treating each event as an idempotent state patch rather than a sequential command.',
        improvements: 'The event log is the biggest gap — when billing support needs to debug an issue, we\'re relying on Stripe\'s dashboard plus app logs. I\'d also split the webhook handler; it grew to handle 12 event types and is hard to reason about now.',
      },
    },
  },
  {
    id: '2',
    name: 'Project Spark AI',
    type: 'AI Tool',
    stack: ['React', 'Python', 'OpenAI', 'FastAPI'],
    roughNotes: 'ai project planner\nyou type a rough idea and it breaks it into tasks\nuses gpt to generate roadmap\nhas a drag and drop board\nsaved projects to db\nhad to handle rate limits and retries',
    cvLine: 'Built Project Spark AI, an AI planning tool that converts rough ideas into structured task roadmaps. Implemented a prompt validation pipeline that brought GPT parse failures from 18% to under 2%, and built a drag-and-drop Kanban board for organizing output.',
    interviewPreview: 'Project Spark AI takes a messy idea and breaks it into a structured task roadmap. The interesting part wasn\'t the AI call — it was making the output reliable enough to actually use. I had to build a validation and retry layer around generation so users didn\'t get malformed responses.',
    fullPitch: {
      elevatorPitch: 'Project Spark AI takes a rough idea — a sentence or two — and breaks it into a structured task roadmap with estimates. Built a validation pipeline around OpenAI output to make it reliably parseable, and a drag-and-drop board to organize the result. Stack: React, FastAPI, OpenAI, PostgreSQL.',
      cvDescription: 'Built Project Spark AI, an AI-powered planning tool that converts rough project descriptions into structured task roadmaps. Implemented a prompt pipeline with Pydantic output validation and retry logic that reduced parse failures from ~18% to under 2%. Built a drag-and-drop Kanban board in React using dnd-kit. Handled OpenAI rate limits with exponential backoff and graceful fallback states. Stack: React, FastAPI, OpenAI API, PostgreSQL.',
      linkedInDescription: 'Shipped Project Spark AI — a tool that turns a vague project idea into an actionable roadmap.\n\nThe interesting problem wasn\'t calling the API. It was making the output reliable.\n\nGPT is good at generating tasks but inconsistent with structure — extra fields, different key names, nested lists where I expected flat arrays. My initial parser broke on roughly 1 in 5 responses.\n\nI fixed it by adding a Pydantic validation layer. If the response doesn\'t match the schema, it retries with a stricter prompt. Parse failures dropped from ~18% to under 2%.\n\nAlso built a drag-and-drop board because the raw generated list wasn\'t useful — people wanted to shuffle priorities, not just read output.\n\nStack: React · FastAPI · OpenAI · PostgreSQL',
      interviewAnswer: 'Project Spark AI came from a personal frustration — I\'d start something new with a vague idea and waste the first few hours just figuring out what to build first.\n\nThe core is a FastAPI backend that takes a rough description, runs it through a designed prompt, and returns a structured task list with estimates and dependencies.\n\nThe challenge was reliability. GPT would sometimes return tasks in a slightly different structure — different key names, nested where I expected flat — which broke my parser. I added a Pydantic model as a validation layer. If the response doesn\'t fit the schema, it retries with a more explicit prompt that constrains the output format. That brought parse failures down from about 18% to under 2%.\n\nI also built the drag-and-drop board because users wanted to shuffle priorities — the raw list wasn\'t interactive enough to be useful day-to-day.',
      technicalBreakdown: {
        architecture: 'FastAPI backend with PostgreSQL. Generation pipeline: receive idea → sanitize input → call OpenAI with function calling → validate output against Pydantic model → retry on schema mismatch → store result → return to client. React frontend with a Kanban board built on dnd-kit.',
        keyDecisions: 'OpenAI function calling over prompt-based JSON — more reliable output structure. Pydantic models for schema enforcement on both input and generation output. Stored roadmaps in the DB so users can revisit without re-generating. Chose FastAPI for fast iteration and first-class Pydantic support.',
        problemsSolved: 'Flaky GPT output: built a validation + retry loop with a stricter prompt on schema failures. Rate limiting: exponential backoff with jitter on 429 responses. Optimistic UI conflicts: held a local draft state and only synced to the server on explicit save, so slow connections don\'t cause visible state jumps.',
        improvements: 'The prompt is hand-tuned and fragile — it would break if the model\'s interpretation of structured prompts changes. I\'d add evals and automated prompt regression tests. Also want to add dependency visualization on the board; right now tasks are flat and don\'t show which ones block others.',
      },
    },
  },
  {
    id: '3',
    name: 'Sculpt Stack Store',
    type: 'E-commerce',
    stack: ['Next.js', 'Shopify API', 'Tailwind', 'Vercel'],
    roughNotes: 'ecommerce storefront\nconnected to shopify\nproduct pages with variants\ncart and checkout flow\nbuilt custom theme\ndeployed on vercel\nhad to handle shopify rate limits',
    cvLine: 'Built Sculpt Stack Store, a headless e-commerce storefront on Shopify\'s Storefront API. Built variant availability logic, a persistent cart, and used ISR to drop median product page load from 800ms to under 100ms.',
    interviewPreview: 'Sculpt Stack Store is a fully custom storefront on top of Shopify — not a template, everything built from the Storefront API up. The hardest part was variant availability: tracking which option combinations exist and showing sold-out states correctly without hammering the API on every selection.',
    fullPitch: {
      elevatorPitch: 'Sculpt Stack Store is a headless Shopify storefront — Shopify handles inventory and payments, I built everything the customer sees. Product pages, variant picker, cart, and checkout handoff, all from scratch. Stack: Next.js, Shopify Storefront API, Tailwind, Vercel.',
      cvDescription: 'Built Sculpt Stack Store, a headless e-commerce storefront powered by the Shopify Storefront API via GraphQL. Implemented product pages with dynamic variant availability logic, a persistent cart with optimistic UI, and a custom checkout handoff. Used ISR to pre-render product pages, reducing median load time from 800ms to under 100ms. Handled Shopify API rate limits with a request queue. Stack: Next.js, Shopify Storefront API, Tailwind CSS, Vercel.',
      linkedInDescription: 'Shipped Sculpt Stack Store — a fully custom Shopify storefront. Not a modified template; every screen built from the Storefront API up.\n\nTwo interesting problems:\n\nVariant availability. Each product has multiple option dimensions (size, color, material) and not every combination exists. I built logic that tracks which values are valid given your current selection, and shows unavailable combinations as greyed-out rather than just missing.\n\nPerformance. The Storefront API has real latency. I used Incremental Static Regeneration to pre-render product pages and only hit the API on revalidation. Median page load dropped from 800ms to under 100ms.\n\nStack: Next.js · Shopify Storefront API · Tailwind · Vercel',
      interviewAnswer: 'Sculpt Stack Store is a headless Shopify storefront — Shopify handles inventory and checkout, but I built the entire frontend rather than using their theme system.\n\nThe client wanted a product experience you can\'t do with Shopify\'s default templates, so I used the Storefront API and built in Next.js.\n\nTwo hard parts: variant logic and performance.\n\nFor variants, each product had multiple options and not every combination existed. I had to build logic that computes which option values are valid given your current selection, and shows unavailable combos as greyed-out rather than just absent — that\'s the UX people expect from good product pages.\n\nFor performance, the Storefront API has latency. I solved it with ISR — pages are statically generated and revalidate in the background on a schedule. That got us under 100ms on median product page loads.\n\nRate limits from Shopify were a problem at scale too — I built a simple request queue with a per-second throttle that queues operations rather than failing them.',
      technicalBreakdown: {
        architecture: 'Next.js app using Shopify Storefront API via GraphQL. Product pages use ISR with a 5-minute revalidation window, plus on-demand revalidation triggered by Shopify inventory webhooks. Cart state is client-side with localStorage persistence, synced to a Shopify cart on checkout initiation. No custom backend — all data flows through the Storefront API.',
        keyDecisions: 'ISR over SSR to avoid Shopify API latency on every request. GraphQL for precise data fetching — the REST API returns too much. Request queue for batch operations to stay under rate limits gracefully. Tailwind for fast iteration on the custom design system.',
        problemsSolved: 'Variant availability matrix: function that takes a product\'s variant list and computes which option values are still valid for each dimension given a partial selection. Rate limits: 2-req/sec throttled queue. Stale product data: webhook-triggered on-demand ISR revalidation when inventory changes in Shopify.',
        improvements: 'Cart sync is fragile — mobile cart state doesn\'t transfer to desktop because it\'s in localStorage. I\'d move to Shopify\'s native cart API. Also want to add proper funnel analytics; right now I can\'t see where people drop off on product pages without looking at server logs.',
      },
    },
  },
  {
    id: '4',
    name: 'Dev Network',
    type: 'Community',
    stack: ['Next.js', 'PostgreSQL', 'WebSockets', 'Redis'],
    roughNotes: 'developer community app\nmatch devs by stack and interests\nreal-time chat with websockets\nprofile pages\nsearch and filter\nhad to figure out the matching algorithm',
    cvLine: 'Built Dev Network, a developer community platform with stack-based matching and real-time chat. Implemented a weighted matching algorithm with a discovery factor, and built the real-time chat layer with Redis pub/sub for multi-instance WebSocket routing.',
    interviewPreview: 'Dev Network connects developers based on what they actually work on — their stack, interests, and project types. Pure similarity matching was useless in practice (you just got clones of yourself), so I had to add a discovery weight based on complementary skills, not just matching ones.',
    fullPitch: {
      elevatorPitch: 'Dev Network matches developers by their actual stack and interests, not just location. Includes real-time chat and profile pages. The matching algorithm balances similarity with discovery — pure cosine similarity just shows you people who are exactly like you. Stack: Next.js, PostgreSQL, WebSockets, Redis.',
      cvDescription: 'Built Dev Network, a developer community platform with stack-based matching, real-time chat, and profile pages. Implemented a weighted matching algorithm that scores across tech stack, experience level, and interests — with a discovery factor that surfaces complementary rather than identical profiles. Built the real-time chat layer on WebSockets with Redis pub/sub for message routing across server instances. Stack: Next.js, PostgreSQL, WebSockets, Redis.',
      linkedInDescription: 'Shipped Dev Network — a developer matchmaking app.\n\nThe core idea: match developers by what they actually build, not just who\'s nearby.\n\nTwo interesting problems:\n\nThe matching algorithm. Pure similarity is useless — you get clones of yourself. I added a discovery weight that surfaces complementary skills alongside similar ones. Took a few iterations before match quality felt good.\n\nMulti-instance WebSocket routing. Single-server WebSockets worked fine, but when I deployed to multiple instances, messages stopped routing correctly. Fixed it with Redis pub/sub — each server subscribes to a channel and broadcasts to its local connections.\n\nStack: Next.js · PostgreSQL · WebSockets · Redis',
      interviewAnswer: 'Dev Network started because every developer networking site felt generic — your profile is a list of technologies and a job title, and matching just means you\'re both in the same city.\n\nI wanted to match on what you actually work on: your stack, project types, whether you\'re looking to collaborate or find a mentor.\n\nThe matching algorithm took a few iterations. The first version was pure cosine similarity on skill vectors. It worked technically, but in practice you\'d get matched with people who are basically you — same stack, same experience level. I added a discovery weight that introduces variance based on complementary skills, not just matching ones. That made results feel more like useful introductions.\n\nThe real-time chat was a separate challenge. Single-server WebSockets worked fine, but when I deployed to multiple instances, messages weren\'t routing correctly — you\'d send a message and it would only reach users connected to the same instance. Fixed it with Redis pub/sub.\n\nIf I were starting over, I\'d build better onboarding. Match quality depends on profile completeness, and most people fill in the minimum required fields.',
      technicalBreakdown: {
        architecture: 'Next.js frontend, Node.js WebSocket server, PostgreSQL for user and message data, Redis for pub/sub and session storage. Match scores are pre-computed by a scheduled job and stored — so the UI query is fast rather than computing on every request.',
        keyDecisions: 'Pre-computed match scores instead of live calculation — matching is expensive and doesn\'t need to be real-time. Redis for WebSocket message routing because the alternative (sticky sessions) breaks with auto-scaling. PostgreSQL for user and relationship data because the schema is relational and benefits from constraints.',
        problemsSolved: 'Multi-instance WebSocket routing: Redis pub/sub. Match score computation time: moved to background scheduled jobs. Profile quality: built a completeness score that gates certain features on how complete your profile is — improved the data quality of the inputs to matching significantly.',
        improvements: 'The matching algorithm is hand-tuned and not rigorously evaluated — I\'d add an A/B testing setup to measure quality by downstream engagement metrics. The cold start problem for new users is also unsolved — first-time match quality is poor until you\'ve filled out a full profile.',
      },
    },
  },
  {
    id: '5',
    name: 'CloudOps Dashboard',
    type: 'Dashboard',
    stack: ['React', 'D3.js', 'Node.js', 'AWS SDK'],
    roughNotes: 'infrastructure monitoring dashboard\nshows server health and alerts\nreal-time charts with d3\naws integration for metrics\nalert rules and notifications\nhad to handle tons of data points without killing the browser',
    cvLine: 'Built CloudOps Dashboard, a real-time infrastructure monitoring tool integrating with AWS CloudWatch. Solved browser performance issues by implementing backend downsampling that preserves anomaly spikes, and windowed D3.js chart rendering for large datasets.',
    interviewPreview: 'CloudOps Dashboard monitors infrastructure health in real time. The performance problem was worse than I expected — minute-level metrics from 40 servers meant 50k+ data points per chart, and the browser would freeze. I had to fix it on both sides: downsampling on the backend and windowed rendering on the frontend.',
    fullPitch: {
      elevatorPitch: 'CloudOps Dashboard is a real-time infrastructure monitoring tool I built for our team. Pulls AWS CloudWatch metrics, evaluates alert rules, and displays server health on a single screen. The main challenge was browser performance at scale — had to implement backend downsampling and windowed D3 rendering. Stack: React, D3.js, Node.js, AWS SDK.',
      cvDescription: 'Built CloudOps Dashboard, a real-time infrastructure monitoring dashboard integrating with AWS CloudWatch for metrics. Implemented a backend downsampling pipeline that aggregates high-frequency data into configurable time windows while preserving min/max envelopes so anomaly spikes aren\'t lost. Built reusable D3.js chart components with windowed rendering to handle 50k+ data points without browser freeze. Stack: React, D3.js, Node.js, AWS SDK.',
      linkedInDescription: 'Shipped CloudOps Dashboard — a real-time infrastructure monitoring tool.\n\nThe naive version: poll CloudWatch, pipe to D3, render charts. That worked until we started ingesting minute-level metrics from 40 servers.\n\nBrowser was choking. Some charts were hitting 50k+ data points and the tab would freeze on scroll.\n\nFix was in two places:\n\nBackend: downsampling that aggregates to configurable time windows (1m, 5m, 1h) but preserves min/max envelopes alongside the average. So alert-relevant spikes don\'t disappear in the smoothed data.\n\nFrontend: windowed chart rendering so only the visible range gets processed by D3.\n\nSmooth now.\n\nStack: React · D3.js · Node.js · AWS SDK',
      interviewAnswer: 'CloudOps Dashboard is an infrastructure monitoring tool I built because our team was managing a growing set of AWS resources and the existing options were either expensive or required three separate tabs to get one coherent view.\n\nI pulled metrics from CloudWatch, built a Node.js backend to aggregate them, and built the dashboard in React with D3 charts.\n\nThe performance problem was harder than I expected. We were pulling CPU, memory, network, and disk metrics at one-minute intervals from about 40 servers. That\'s a lot of data, and D3 tries to render all of it.\n\nI fixed it in two places. On the backend, I built a downsampling step that collapses data into configurable time windows — 5m, 1h, 6h — but preserves the min/max envelope alongside the average so anomaly spikes aren\'t smoothed away. On the frontend, I implemented windowed rendering so only the data currently in view gets processed.\n\nThe alerting system was also non-trivial. Rate-of-change rules — "alert if CPU rises more than 30% in 5 minutes" — required thinking carefully about how to evaluate time series rather than just comparing against thresholds.',
      technicalBreakdown: {
        architecture: 'React frontend, Node.js backend that polls AWS CloudWatch on a schedule and stores aggregated metrics in PostgreSQL. A separate process evaluates alert rules against incoming data and publishes alerts via WebSocket to connected clients. D3.js for chart rendering with custom tooltip, zoom, and multi-axis behavior.',
        keyDecisions: 'Custom downsampling over an off-the-shelf time-series DB — I needed control over how anomalies were preserved during aggregation. D3 over a chart library because the visualization requirements were too specific for higher-level abstractions. Alert rules stored as JSON expressions evaluated server-side so clients don\'t need to receive raw data.',
        problemsSolved: 'Chart performance: windowed rendering on the frontend, backend downsampling with anomaly preservation. AWS API rate limits: batched metric queries with exponential backoff. Alert false positives: smoothed input data with a rolling average before rule evaluation to reduce noise from one-off spikes.',
        improvements: 'The alert rule builder is too technical — only engineers can write rules right now. I\'d add a UI builder with plain-language descriptions. Also the PostgreSQL time-series table degrades on queries over long ranges; I\'d evaluate moving to TimescaleDB or InfluxDB for that layer.',
      },
    },
  },
  {
    id: '6',
    name: 'TaskPilot',
    type: 'Dashboard',
    stack: ['Vue.js', 'Supabase', 'Tailwind', 'Vite'],
    roughNotes: 'productivity dashboard\ntask management with categories\ntime tracking built in\ndaily/weekly views\nsyncs across devices\nhad to make the offline mode work reliably',
    cvLine: 'Built TaskPilot, a productivity app combining task management and time tracking with offline-first sync. Implemented conflict resolution for concurrent offline edits across devices, with status-aware merge logic to prevent completed tasks from reverting.',
    interviewPreview: 'TaskPilot combines task management and time tracking in one app — I built it because every tool I tried did one or the other, and keeping them in sync was too much friction. The hard part was offline sync: making changes made without internet survive reconnection without clobbering work done on another device.',
    fullPitch: {
      elevatorPitch: 'TaskPilot combines task management with time tracking in one app, with reliable offline sync. The technical challenge was conflict resolution — changes made offline on different devices need to merge without data loss. Stack: Vue.js, Supabase, IndexedDB, Tailwind, Vite.',
      cvDescription: 'Built TaskPilot, a productivity app combining task management with integrated time tracking and offline-first sync. Implemented a conflict resolution system for concurrent offline edits: last-write-wins for most fields, with status-aware merge logic that prevents completed tasks from being overwritten by stale in-progress states from other devices. Used IndexedDB for local storage and Supabase Realtime for sync. Stack: Vue.js, Supabase, Tailwind CSS, Vite.',
      linkedInDescription: 'Shipped TaskPilot — a productivity app that combines task management and time tracking in one place.\n\nThe interesting part was offline sync.\n\nMost of my use case is on trains or in places without wifi. I needed changes made offline to sync correctly when connection returned — without overwriting changes made on another device in the meantime.\n\nFirst version: sync everything on reconnect. Broke immediately as soon as I used two devices. Completing a task on my phone would revert to in-progress when my laptop reconnected with stale state.\n\nFix: last-write-wins for most fields, but status transitions are modelled as an ordered set — only forward transitions are allowed. "Complete" can\'t be overwritten by "in-progress" regardless of timestamp.\n\nTook three iterations. The conflict cases you don\'t think of upfront are always the tricky ones.\n\nStack: Vue.js · Supabase · IndexedDB · Tailwind',
      interviewAnswer: 'TaskPilot started because I kept using two apps — one for tasks, one for time — and the friction of keeping them in sync meant I\'d always let one slip.\n\nOffline-first was a core requirement because I use it on trains and in places without reliable wifi.\n\nThe offline sync was the genuinely hard part. The first version used a simple "sync everything on reconnect" approach. That failed as soon as I used the app on two devices — I\'d complete a task on my phone, then reconnect my laptop and the task would revert to in-progress because the laptop had an older state.\n\nI had to build a conflict resolution layer. Most fields use last-write-wins based on timestamp. But task status needs special handling — "complete" should never be overwritten by a stale "in-progress" from a slow-syncing device. I modelled status transitions as an ordered set and only allowed forward transitions during merges.\n\nI also learned that IndexedDB is finicky. Browser storage limits, schema migrations, and cache-clearing bugs took a while to track down.',
      technicalBreakdown: {
        architecture: 'Vue.js frontend with Supabase for auth, database, and real-time subscriptions. Local state in IndexedDB for offline support. A sync manager handles the lifecycle: queue changes offline → apply to Supabase on reconnect → run conflict resolution before committing → broadcast updates via Supabase Realtime.',
        keyDecisions: 'Supabase over a custom backend to get real-time subscriptions without building them. IndexedDB over localStorage because task data is structured and too large for localStorage. Vue.js reactivity system works cleanly for this kind of data-heavy, frequently-updating UI. Vite for significantly faster hot reload during development.',
        problemsSolved: 'Offline sync conflicts: custom conflict resolution with last-write-wins plus ordered-set status merge. IndexedDB schema migrations: version-based migration system modelled after database migrations. Time tracking drift: the running timer was losing seconds on tab hide — fixed by storing an absolute start timestamp and computing elapsed on read rather than incrementing a counter.',
        improvements: 'The conflict resolution logic is scattered across the sync manager and individual store actions — it should be centralized in one place. Recurring tasks are also missing; the data model for recurrence rules is complex and I haven\'t gotten the design right. Performance on the weekly view degrades with large task histories and needs virtual scrolling.',
      },
    },
  },
];

export const savedExamples: SavedExample[] = exampleProjects.map((ep) => ({
  id: ep.id,
  name: ep.name,
  type: ep.type === 'SaaS' ? 'saas' : ep.type === 'AI Tool' ? 'ai-tool' : ep.type === 'E-commerce' ? 'ecommerce' : ep.type === 'Dashboard' ? 'dashboard' : 'other',
  pitch: ep.fullPitch,
}));
